spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: ALWAYS

sap:
  client:
    host: https://fiap-reactjs-presencial.herokuapp.com

banck:
  client:
    host: https://fiap-reactjs-presencial.herokuapp.com
